// Test definitions. Do NOT edit this file!

#define CATCH_CONFIG_MAIN // defines main() automatically

#include <catch2/catch.hpp>

// =====================
// tests for exercise 1
// ---------------------

TEST_CASE("Ex1", "[Suma]")
{
    REQUIRE(suma(1,1) == 2);
}

// =====================
// tests for exercise 2
// ---------------------

TEST_CASE("Ex2", "[resta]")
{
    REQUIRE(resta(5,3) == 2);
}

// =====================
// tests for exercise 3
// ---------------------

TEST_CASE("Ex3", "[multiplicacion]")
{
    REQUIRE(multiplica(5,3) == 15);
}

// =====================
// tests for exercise 4
// ---------------------

TEST_CASE("Ex4", "[division]")
{
    REQUIRE(divide(12,3) == 4);
}

